/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPacakge;

import GamePackage.Control;
import StrategiesPackage.EasyStrategy;
import StrategiesPackage.HardStrategy;
import StrategiesPackage.MediumStrategy;

/**
 *
 * @author Mohamed Elkalaf
 */
public class DifficaltyPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiffuicaltyPanel
     */
    
    private static DifficaltyPanel difficaltyPanel;
    
    private DifficaltyPanel() {
        initComponents();
    }
    
    public static DifficaltyPanel OpenDifficaltyPanel()
    {
        if(difficaltyPanel==null)
            difficaltyPanel= new DifficaltyPanel();
        return difficaltyPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        EASY = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        MEDIUM = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        HARD = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(204, 51, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel12.setBackground(new java.awt.Color(51, 51, 51));
        jPanel12.setLayout(new java.awt.GridLayout(1, 2, 0, 1));

        jPanel13.setLayout(new java.awt.BorderLayout());

        EASY.setBackground(new java.awt.Color(255, 255, 255));
        EASY.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        EASY.setForeground(new java.awt.Color(0, 153, 51));
        EASY.setText("EASY");
        EASY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EASYActionPerformed(evt);
            }
        });
        jPanel13.add(EASY, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        MEDIUM.setBackground(new java.awt.Color(255, 255, 255));
        MEDIUM.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        MEDIUM.setForeground(new java.awt.Color(255, 153, 0));
        MEDIUM.setText("MEDIUM");
        MEDIUM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIUMActionPerformed(evt);
            }
        });
        jPanel14.add(MEDIUM, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        HARD.setBackground(new java.awt.Color(255, 255, 255));
        HARD.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        HARD.setForeground(new java.awt.Color(255, 0, 0));
        HARD.setText("HARD");
        HARD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARDActionPerformed(evt);
            }
        });
        jPanel15.add(HARD, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel15);

        jPanel6.add(jPanel12, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XOGAME");
        jPanel6.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void EASYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EASYActionPerformed
        Control control = Control.StartControl(true,EasyStrategy.start(),false,null);
        this.setVisible(false);
    }//GEN-LAST:event_EASYActionPerformed

    private void MEDIUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIUMActionPerformed
        Control control = Control.StartControl(true,MediumStrategy.start(),false,null);
        this.setVisible(false);
    }//GEN-LAST:event_MEDIUMActionPerformed

    private void HARDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARDActionPerformed
        Control control = Control.StartControl(true,HardStrategy.start(),false,null);
        this.setVisible(false);
    }//GEN-LAST:event_HARDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EASY;
    private javax.swing.JButton HARD;
    private javax.swing.JButton MEDIUM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
