/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPacakge;

import GamePackage.Control;
import MementoPacckage.Memento;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Mohamed Elkalaf
 */
public class LoadPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoadPanel
     */
    
    private static LoadPanel loadPanel;
    private final ArrayList<Memento> mementos;
    private final JButton[] buttons;
    private int Mementocounter=0;
    
    private LoadPanel() {
        initComponents();
                mementos = new ArrayList<>();
        buttons=new JButton[15];
        buttons[0]=Game1;
        buttons[1]=Game2;
        buttons[2]=Game3;
        buttons[3]=Game4;
        buttons[4]=Game5;
        buttons[5]=Game6;
        buttons[6]=Game7;
        buttons[7]=Game8;
        buttons[8]=Game9;
        buttons[9]=Game10;
        buttons[10]=Game11;
        buttons[11]=Game12;
        buttons[12]=Game13;
        buttons[13]=Game14;
        buttons[14]=Game15;
        for(int i=0;i<15;i++)
            buttons[i].setEnabled(false);
    }
    
    public static LoadPanel OpenLoadPanel()
    {
        if(loadPanel==null)
            loadPanel= new LoadPanel();
        return loadPanel;
    }

     public void addNewMemento(Memento memento)
    {
        if(Mementocounter<15)
        {
            buttons[Mementocounter].setEnabled(true);
            buttons[Mementocounter].setText("Game"+String.valueOf(Mementocounter+1));
            mementos.add(memento);
            Mementocounter++;
        }
    }
     
     private void OpenMemento(int i)
    {
        Control control = Control.StartControl(mementos.get(i).onePlayer(),mementos.get(i).getStrategy(),true,mementos.get(i));
       this.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Game1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Game2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Game3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Game4 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Game5 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Game6 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Game7 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Game8 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        Game9 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        Game10 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        Game11 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        Game12 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        Game13 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        Game14 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        Game15 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XOGAME");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        Game1.setBackground(new java.awt.Color(255, 255, 255));
        Game1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game1ActionPerformed(evt);
            }
        });
        jPanel3.add(Game1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        Game2.setBackground(new java.awt.Color(255, 255, 255));
        Game2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game2ActionPerformed(evt);
            }
        });
        jPanel4.add(Game2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        Game3.setBackground(new java.awt.Color(255, 255, 255));
        Game3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game3ActionPerformed(evt);
            }
        });
        jPanel5.add(Game3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 51, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        Game4.setBackground(new java.awt.Color(255, 255, 255));
        Game4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game4ActionPerformed(evt);
            }
        });
        jPanel6.add(Game4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 51, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        Game5.setBackground(new java.awt.Color(255, 255, 255));
        Game5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game5ActionPerformed(evt);
            }
        });
        jPanel7.add(Game5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());

        Game6.setBackground(new java.awt.Color(255, 255, 255));
        Game6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game6ActionPerformed(evt);
            }
        });
        jPanel8.add(Game6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        Game7.setBackground(new java.awt.Color(255, 255, 255));
        Game7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game7ActionPerformed(evt);
            }
        });
        jPanel9.add(Game7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        Game8.setBackground(new java.awt.Color(255, 255, 255));
        Game8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game8ActionPerformed(evt);
            }
        });
        jPanel10.add(Game8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(204, 51, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());

        Game9.setBackground(new java.awt.Color(255, 255, 255));
        Game9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game9ActionPerformed(evt);
            }
        });
        jPanel11.add(Game9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 51, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        Game10.setBackground(new java.awt.Color(255, 255, 255));
        Game10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game10ActionPerformed(evt);
            }
        });
        jPanel12.add(Game10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        Game11.setBackground(new java.awt.Color(255, 255, 255));
        Game11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game11ActionPerformed(evt);
            }
        });
        jPanel13.add(Game11, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        Game12.setBackground(new java.awt.Color(255, 255, 255));
        Game12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game12ActionPerformed(evt);
            }
        });
        jPanel14.add(Game12, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        Game13.setBackground(new java.awt.Color(255, 255, 255));
        Game13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game13ActionPerformed(evt);
            }
        });
        jPanel15.add(Game13, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new java.awt.BorderLayout());

        Game14.setBackground(new java.awt.Color(255, 255, 255));
        Game14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game14ActionPerformed(evt);
            }
        });
        jPanel16.add(Game14, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new java.awt.BorderLayout());

        Game15.setBackground(new java.awt.Color(255, 255, 255));
        Game15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Game15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Game15ActionPerformed(evt);
            }
        });
        jPanel17.add(Game15, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void Game1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game1ActionPerformed
        OpenMemento(0);
    }//GEN-LAST:event_Game1ActionPerformed

    private void Game2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game2ActionPerformed
        OpenMemento(1);
    }//GEN-LAST:event_Game2ActionPerformed

    private void Game3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game3ActionPerformed
        OpenMemento(2);
    }//GEN-LAST:event_Game3ActionPerformed

    private void Game4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game4ActionPerformed
        OpenMemento(3);
    }//GEN-LAST:event_Game4ActionPerformed

    private void Game5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game5ActionPerformed
        OpenMemento(4);
    }//GEN-LAST:event_Game5ActionPerformed

    private void Game6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game6ActionPerformed
        OpenMemento(5);
    }//GEN-LAST:event_Game6ActionPerformed

    private void Game7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game7ActionPerformed
        OpenMemento(6);
    }//GEN-LAST:event_Game7ActionPerformed

    private void Game8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game8ActionPerformed
        OpenMemento(7);
    }//GEN-LAST:event_Game8ActionPerformed

    private void Game9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game9ActionPerformed
        OpenMemento(8);
    }//GEN-LAST:event_Game9ActionPerformed

    private void Game10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game10ActionPerformed
        OpenMemento(9);
    }//GEN-LAST:event_Game10ActionPerformed

    private void Game11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game11ActionPerformed
        OpenMemento(10);
    }//GEN-LAST:event_Game11ActionPerformed

    private void Game12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game12ActionPerformed
        OpenMemento(11);
    }//GEN-LAST:event_Game12ActionPerformed

    private void Game13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game13ActionPerformed
        OpenMemento(12);
    }//GEN-LAST:event_Game13ActionPerformed

    private void Game14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game14ActionPerformed
        OpenMemento(13);
    }//GEN-LAST:event_Game14ActionPerformed

    private void Game15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Game15ActionPerformed
        OpenMemento(14);
    }//GEN-LAST:event_Game15ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Game1;
    private javax.swing.JButton Game10;
    private javax.swing.JButton Game11;
    private javax.swing.JButton Game12;
    private javax.swing.JButton Game13;
    private javax.swing.JButton Game14;
    private javax.swing.JButton Game15;
    private javax.swing.JButton Game2;
    private javax.swing.JButton Game3;
    private javax.swing.JButton Game4;
    private javax.swing.JButton Game5;
    private javax.swing.JButton Game6;
    private javax.swing.JButton Game7;
    private javax.swing.JButton Game8;
    private javax.swing.JButton Game9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
