/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewPacakge;

import GamePackage.Control;
import StrategiesPackage.EasyStrategy;
import javax.swing.JButton;

/**
 *
 * @author Mohamed Elkalaf
 */
public class SelectPanel extends javax.swing.JPanel {

    /**
     * Creates new form SelectPanel
     */
    
    private static SelectPanel selectPanel;
    
    private SelectPanel() {
        initComponents();
        Loadbtn.setEnabled(false);
    }
    
    public JButton getLoadBtn()
    {
        return Loadbtn;
    }
    
    public static SelectPanel OpenSelectPanel()
    {
        if(selectPanel==null)
            selectPanel= new SelectPanel();
        return selectPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OnePlayerbtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        TwoPlayerbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Loadbtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("XOGAME");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        jPanel3.setLayout(new java.awt.BorderLayout());

        OnePlayerbtn.setBackground(new java.awt.Color(255, 255, 255));
        OnePlayerbtn.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        OnePlayerbtn.setForeground(new java.awt.Color(204, 0, 204));
        OnePlayerbtn.setText("ONE PLAYER");
        OnePlayerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnePlayerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(OnePlayerbtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        TwoPlayerbtn.setBackground(new java.awt.Color(255, 255, 255));
        TwoPlayerbtn.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        TwoPlayerbtn.setForeground(new java.awt.Color(204, 0, 204));
        TwoPlayerbtn.setText("TWOPLAYERS");
        TwoPlayerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoPlayerbtnActionPerformed(evt);
            }
        });
        jPanel4.add(TwoPlayerbtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        Loadbtn.setBackground(new java.awt.Color(255, 255, 255));
        Loadbtn.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Loadbtn.setForeground(new java.awt.Color(204, 0, 204));
        Loadbtn.setText(" LOAD GAME");
        Loadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadbtnActionPerformed(evt);
            }
        });
        jPanel5.add(Loadbtn, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void OnePlayerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnePlayerbtnActionPerformed
        DifficaltyPanel f =DifficaltyPanel.OpenDifficaltyPanel();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_OnePlayerbtnActionPerformed

    private void TwoPlayerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoPlayerbtnActionPerformed
        Control control = Control.StartControl(false,EasyStrategy.start(),false,null);
        this.setVisible(false);
    }//GEN-LAST:event_TwoPlayerbtnActionPerformed

    private void LoadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadbtnActionPerformed
        LoadPanel m=LoadPanel.OpenLoadPanel();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoadbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loadbtn;
    private javax.swing.JButton OnePlayerbtn;
    private javax.swing.JButton TwoPlayerbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
